# Generated by Django 2.0.6 on 2018-06-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='beta_user',
            field=models.BooleanField(default=False, help_text='Test and help us find bugs in our unreleased features'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, help_text='Your date of birth', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail_notifications_allowed',
            field=models.BooleanField(default=True, help_text='Get all your notifications via mail'),
        ),
        migrations.AddField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(default=True, help_text='Get notifications our new services and features'),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_gravtar',
            field=models.BooleanField(default=False, help_text='One avtar to rule them all!'),
        ),
    ]
