# Generated by Django 2.0.6 on 2018-06-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_profile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
    ]
