# Generated by Django 2.0.6 on 2018-06-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_small',
            field=models.URLField(help_text='Profile picture smaller URL', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(help_text='Profile picture URL', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='use_gravtar',
            field=models.BooleanField(default=False, help_text='One avatar to rule them all!'),
        ),
    ]
