# Generated by Django 2.0.6 on 2018-06-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20180627_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other'), ('n', 'Not Specified')], max_length=9, null=True),
        ),
    ]
