# Generated by Django 2.0.6 on 2018-06-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20180627_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, help_text='Profile picture URL', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_small',
            field=models.URLField(blank=True, help_text='Profile picture smaller URL', null=True),
        ),
    ]
