# Generated by Django 2.0.6 on 2018-07-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20180705_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landing.Country'),
        ),
    ]
