# Generated by Django 2.0.5 on 2018-08-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_profile_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_verified',
            new_name='email_confirmed',
        ),
    ]
