# Generated by Django 2.0.6 on 2018-07-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
