# Generated by Django 2.0.7 on 2018-07-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20180716_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
