# Generated by Django 2.0.7 on 2018-07-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospital_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='state',
        ),
    ]
