# Generated by Django 2.0.6 on 2018-07-17 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20180716_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
