# Generated by Django 2.0.7 on 2018-07-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20180720_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialisation',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
