# Generated by Django 2.0.5 on 2018-07-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20180725_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='You can choose appointment duration as maximum of 7 days', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='You can choose dates from now', null=True),
        ),
    ]
