# Generated by Django 2.0.5 on 2018-07-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_hospital_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
