# Generated by Django 2.0.5 on 2018-07-27 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_hospital_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Please enter valid email, it will be used for verification.', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:\\ '+919999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
