# Generated by Django 2.0.5 on 2018-07-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20180727_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-start_date',), 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='You can choose appointment duration as maximum of 7 days', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='You can choose dates from now', null=True),
        ),
    ]
