# Generated by Django 2.0.6 on 2018-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20180731_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejection_cause',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
